version: '3.8'

services:
  app:
    image: "undercooked_app"
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - JWT_SECRET=${JWT_SECRET}
      - EXPIRATION=${EXPIRATION}
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: 'postgres:15.6-alpine'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}